### ISSUE TITLE
如何避免node_modules目录里属于devDependencies的包不上传

### ISSUE THREAD

**Issue by BetterLuke** [serverless-components/tencent-nestjs#11]
RT：如何避免node_modules目录里属于devDependencies的包不上传

目前我是自己手动在serverless.yml的配置exclude属性，官方有没有类似于插件的机制可以统一处理。

**Comment by yugasun** [comment]
@BetterLuke 可以在执行 `build` 命令后执行 `npm install --production`，比如你在 `package.json` 中的 `build` 命令可以改为：

```bash
"build": "nest build && npm install --production"
```

当然还可以借助社区其他工具来精简你的 `dependencies` ，比如 `node-prune`，或者 `yarn autoclean` 命令....

**Comment by BetterLuke** [comment]
> @BetterLuke 可以在执行 `build` 命令后执行 `npm install --production`，比如你在 `package.json` 中的 `build` 命令可以改为：
> 
> ```shell
> "build": "nest build && npm install --production"
> ```
> 
> 当然还可以借助社区其他工具来精简你的 `dependencies` ，比如 `node-prune`，或者 `yarn autoclean` 命令....

感谢大佬的回复，最近在个人项目上试用你们的产品，无论产品还是社区的回复，真的赞👍，谢谢。

试用你提供的建议，node_modules的黑洞体积减少了一半，再次感谢🙏

**Comment by yugasun** [comment]
@BetterLuke 客气了

**Comment by yugasun** [comment]
也可以尝试下 [@slsplus/node-prune](https://github.com/serverless-plus/node-prune) 工具

**Comment by BetterLuke** [comment]
> 也可以尝试下 [@slsplus/node-prune](https://github.com/serverless-plus/node-prune) 工具

大佬出品，必属精品~
