### ISSUE TITLE
为什么部署完打开不是hello word?

### ISSUE THREAD

**Issue by tingshuai** [serverless-components/tencent-nestjs#13]
![WE(8$XG~6OT~{%8QRGOD~AO](https://user-images.githubusercontent.com/23158246/117937857-00088c00-b339-11eb-9e3f-af7a5eaf8af6.png)
打开不应该是hello word 吗，怎么显示的是这？

**Comment by yugasun** [comment]
这就是一个部署显示静态页面的案例，开发者可根据个人需求修改页面内容
