### ISSUE TITLE
sls.js es6导出后部署完访问报错

### ISSUE THREAD

**Issue by tingshuai** [serverless-components/tencent-nestjs#14]
![image](https://user-images.githubusercontent.com/23158246/118068914-c6399300-b3d5-11eb-9830-c68ddd92d806.png)

<img width="1262" alt="微信图片_20210513101643" src="https://user-images.githubusercontent.com/23158246/118068523-12380800-b3d5-11eb-908a-68b9e384b299.png">

**Comment by yugasun** [comment]
部署前项目是需要改造的，参考文档：https://github.com/serverless-components/tencent-nestjs#%E9%A1%B9%E7%9B%AE%E6%94%B9%E9%80%A0，或者直接使用项目 `example` 文件夹示例，改造后，项目是需要编译成 js，云函数不支持 `import` 语法。

**Comment by tingshuai** [comment]
> 云函数不支持 `import` 语法。

ok
