### ISSUE TITLE
如何查看日志

### ISSUE THREAD

**Issue by levy9527** [serverless-components/tencent-nestjs#2]
你好，请问如何查看日志呢？

我的目录如下：
![image](https://user-images.githubusercontent.com/9384365/96835164-c98b2280-1475-11eb-90ae-555c2a22d121.png)

我目前是进入到 nest-starter 目录下输入命令：
```sh
sls logs -f $funcName
```
结果报错：

```sh
1s › serverless-api › Error: Component does not have the method: "logs"
```

**Comment by yugasun** [comment]
@levy9527 暂不支持本地查看日志呢，可以通过登录 [云函数控制台](https://console.cloud.tencent.com/scf) 查看。

**Comment by levy9527** [comment]
😂 好吧，我还以为自己姿势不对。还是感谢你，使用你封装的组件方便很多👍

**Comment by levy9527** [comment]
再请问下，现在 云函数控制台 的日志，是平台自带的日志，没有我在应用中输出的日志（直接输出在 stdout 中），我应该怎么做呢。
